import Testing

@testable import AdventOfCode

struct Day08Tests {
  let testData = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............

    """

  @Test func testPart1() async throws {
    let challenge = Day08(data: testData)
    try await #expect(String(describing: challenge.part1()) == "14")
  }
}
